data:
 build: jenkins-data
master:
 build: jenkins-master
 volumes_from:
  - data
 volumes:
  - ./jenkinslocation.txt:/myfiles/jenkinslocation.txt
 ports:
  - "50000:50000"
nginx:
 build: jenkins-nginx
 ports:
  - "80:80"
 links:
  - master:jenkins-master
slave:
 build: jenkins-slave
proxy:
 image: ehazlett/docker-proxy:latest
 command: -i
 ports:
  - "3375:2375"
 volumes:
  - /var/run/docker.sock:/var/run/docker.sock 

